[from-internal]
exten => 555,1,Answer()
 same => n,Set(CALL_TYPE=inbound)
 same => n,Stasis(ai-bot)
 same => n,Hangup()

exten => 6002,1,NoOp(Call Bot for 6002)
 same => n,Set(CALL_TYPE=outbound)
 same => n,Stasis(ai-bot)
 same => n,Hangup()